<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="25705" started-at="2018-03-17T05:21:19Z" finished-at="2018-03-17T05:21:45Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="25705" started-at="2018-03-17T05:21:19Z" finished-at="2018-03-17T05:21:45Z">
      <class name="AutomationTest.AutomationTest9">
        <test-method status="PASS" signature="BeforeAT8()[pri:0, instance:AutomationTest.AutomationTest9@d25987]" name="BeforeAT8" is-config="true" duration-ms="12932" started-at="2018-03-17T10:51:19Z" finished-at="2018-03-17T10:51:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeAT8 -->
        <test-method status="FAIL" signature="AT8()[pri:0, instance:AutomationTest.AutomationTest9@d25987]" name="AT8" duration-ms="12632" started-at="2018-03-17T10:51:32Z" finished-at="2018-03-17T10:51:45Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [YOUR ORDER HAS BEEN RECEIVED] but found [CHECKOUT]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [YOUR ORDER HAS BEEN RECEIVED] but found [CHECKOUT]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at AutomationTest.AutomationTest9.AT8(AutomationTest9.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AT8 -->
        <test-method status="PASS" signature="AfterAT8()[pri:0, instance:AutomationTest.AutomationTest9@d25987]" name="AfterAT8" is-config="true" duration-ms="110" started-at="2018-03-17T10:51:45Z" finished-at="2018-03-17T10:51:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterAT8 -->
      </class> <!-- AutomationTest.AutomationTest9 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
